/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.audience.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AudienceEntry service. Represents a row in the &quot;AudienceEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.audience.model.impl.AudienceEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.audience.model.impl.AudienceEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AudienceEntry
 * @generated
 */
@ProviderType
public interface AudienceEntryModel
	extends AuditedModel, BaseModel<AudienceEntry>, ExternalReferenceCodeModel,
			MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audience entry model instance should use the {@link AudienceEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this audience entry.
	 *
	 * @return the primary key of this audience entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audience entry.
	 *
	 * @param primaryKey the primary key of this audience entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this audience entry.
	 *
	 * @return the mvcc version of this audience entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this audience entry.
	 *
	 * @param mvccVersion the mvcc version of this audience entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the external reference code of this audience entry.
	 *
	 * @return the external reference code of this audience entry
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this audience entry.
	 *
	 * @param externalReferenceCode the external reference code of this audience entry
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the audience entry ID of this audience entry.
	 *
	 * @return the audience entry ID of this audience entry
	 */
	public long getAudienceEntryId();

	/**
	 * Sets the audience entry ID of this audience entry.
	 *
	 * @param audienceEntryId the audience entry ID of this audience entry
	 */
	public void setAudienceEntryId(long audienceEntryId);

	/**
	 * Returns the company ID of this audience entry.
	 *
	 * @return the company ID of this audience entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this audience entry.
	 *
	 * @param companyId the company ID of this audience entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this audience entry.
	 *
	 * @return the user ID of this audience entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this audience entry.
	 *
	 * @param userId the user ID of this audience entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audience entry.
	 *
	 * @return the user uuid of this audience entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this audience entry.
	 *
	 * @param userUuid the user uuid of this audience entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this audience entry.
	 *
	 * @return the user name of this audience entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this audience entry.
	 *
	 * @param userName the user name of this audience entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this audience entry.
	 *
	 * @return the create date of this audience entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this audience entry.
	 *
	 * @param createDate the create date of this audience entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this audience entry.
	 *
	 * @return the modified date of this audience entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this audience entry.
	 *
	 * @param modifiedDate the modified date of this audience entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the json of this audience entry.
	 *
	 * @return the json of this audience entry
	 */
	@AutoEscape
	public String getJSON();

	/**
	 * Sets the json of this audience entry.
	 *
	 * @param json the json of this audience entry
	 */
	public void setJSON(String json);

	/**
	 * Returns the name of this audience entry.
	 *
	 * @return the name of this audience entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this audience entry.
	 *
	 * @param name the name of this audience entry
	 */
	public void setName(String name);

	@Override
	public AudienceEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:768827737