modified.files.includes[relevant][audience-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][audience-web-playwright-rule]=\
    audience-web.main

relevant.rule.names=audience-web-playwright-rule

test.batch.names[relevant][audience-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163