/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.audience.model.impl;

import com.liferay.audience.model.AudienceEntry;
import com.liferay.audience.model.AudienceEntryModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AudienceEntry service. Represents a row in the &quot;AudienceEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AudienceEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AudienceEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AudienceEntryImpl
 * @generated
 */
@JSON(strict = true)
public class AudienceEntryModelImpl
	extends BaseModelImpl<AudienceEntry> implements AudienceEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audience entry model instance should use the <code>AudienceEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "AudienceEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"externalReferenceCode", Types.VARCHAR},
		{"audienceEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"json", Types.CLOB}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("audienceEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("json", Types.CLOB);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AudienceEntry (mvccVersion LONG default 0 not null,externalReferenceCode VARCHAR(75) null,audienceEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,json TEXT null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AudienceEntry";

	public static final String ENTITY_ALIAS = "audienceEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY audienceEntry.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AudienceEntry.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AudienceEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _audienceEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAudienceEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _audienceEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AudienceEntry.class;
	}

	@Override
	public String getModelClassName() {
		return AudienceEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AudienceEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AudienceEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AudienceEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AudienceEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AudienceEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AudienceEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AudienceEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AudienceEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AudienceEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AudienceEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AudienceEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AudienceEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", AudienceEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				AudienceEntry::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"audienceEntryId", AudienceEntry::getAudienceEntryId);
			attributeGetterFunctions.put(
				"companyId", AudienceEntry::getCompanyId);
			attributeGetterFunctions.put("userId", AudienceEntry::getUserId);
			attributeGetterFunctions.put(
				"userName", AudienceEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", AudienceEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AudienceEntry::getModifiedDate);
			attributeGetterFunctions.put("json", AudienceEntry::getJSON);
			attributeGetterFunctions.put("name", AudienceEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AudienceEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AudienceEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AudienceEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<AudienceEntry, Long>)AudienceEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<AudienceEntry, String>)
					AudienceEntry::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"audienceEntryId",
				(BiConsumer<AudienceEntry, Long>)
					AudienceEntry::setAudienceEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AudienceEntry, Long>)AudienceEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AudienceEntry, Long>)AudienceEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AudienceEntry, String>)AudienceEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AudienceEntry, Date>)AudienceEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AudienceEntry, Date>)
					AudienceEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"json",
				(BiConsumer<AudienceEntry, String>)AudienceEntry::setJSON);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<AudienceEntry, String>)AudienceEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getAudienceEntryId() {
		return _audienceEntryId;
	}

	@Override
	public void setAudienceEntryId(long audienceEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_audienceEntryId = audienceEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getJSON() {
		if (_json == null) {
			return "";
		}
		else {
			return _json;
		}
	}

	@Override
	public void setJSON(String json) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_json = json;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AudienceEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AudienceEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AudienceEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AudienceEntryImpl audienceEntryImpl = new AudienceEntryImpl();

		audienceEntryImpl.setMvccVersion(getMvccVersion());
		audienceEntryImpl.setExternalReferenceCode(getExternalReferenceCode());
		audienceEntryImpl.setAudienceEntryId(getAudienceEntryId());
		audienceEntryImpl.setCompanyId(getCompanyId());
		audienceEntryImpl.setUserId(getUserId());
		audienceEntryImpl.setUserName(getUserName());
		audienceEntryImpl.setCreateDate(getCreateDate());
		audienceEntryImpl.setModifiedDate(getModifiedDate());
		audienceEntryImpl.setJSON(getJSON());
		audienceEntryImpl.setName(getName());

		audienceEntryImpl.resetOriginalValues();

		return audienceEntryImpl;
	}

	@Override
	public AudienceEntry cloneWithOriginalValues() {
		AudienceEntryImpl audienceEntryImpl = new AudienceEntryImpl();

		audienceEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		audienceEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		audienceEntryImpl.setAudienceEntryId(
			this.<Long>getColumnOriginalValue("audienceEntryId"));
		audienceEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		audienceEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		audienceEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		audienceEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		audienceEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		audienceEntryImpl.setJSON(this.<String>getColumnOriginalValue("json"));
		audienceEntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return audienceEntryImpl;
	}

	@Override
	public int compareTo(AudienceEntry audienceEntry) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), audienceEntry.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AudienceEntry)) {
			return false;
		}

		AudienceEntry audienceEntry = (AudienceEntry)object;

		long primaryKey = audienceEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AudienceEntry> toCacheModel() {
		AudienceEntryCacheModel audienceEntryCacheModel =
			new AudienceEntryCacheModel();

		audienceEntryCacheModel.mvccVersion = getMvccVersion();

		audienceEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			audienceEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			audienceEntryCacheModel.externalReferenceCode = null;
		}

		audienceEntryCacheModel.audienceEntryId = getAudienceEntryId();

		audienceEntryCacheModel.companyId = getCompanyId();

		audienceEntryCacheModel.userId = getUserId();

		audienceEntryCacheModel.userName = getUserName();

		String userName = audienceEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			audienceEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			audienceEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			audienceEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			audienceEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			audienceEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		audienceEntryCacheModel.json = getJSON();

		String json = audienceEntryCacheModel.json;

		if ((json != null) && (json.length() == 0)) {
			audienceEntryCacheModel.json = null;
		}

		audienceEntryCacheModel.name = getName();

		String name = audienceEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			audienceEntryCacheModel.name = null;
		}

		return audienceEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AudienceEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AudienceEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AudienceEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AudienceEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AudienceEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AudienceEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _externalReferenceCode;
	private long _audienceEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _json;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<AudienceEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AudienceEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("audienceEntryId", _audienceEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("json", _json);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("audienceEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("json", 256L);

		columnBitmasks.put("name", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AudienceEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1231800925